# Generated by Django 5.0 on 2023-12-26 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_todolist_job_type_alter_todolist_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='toDoLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('date', models.DateField(default=datetime.date.today)),
                ('job', models.CharField(max_length=255)),
                ('status', models.BooleanField()),
                ('job_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='toDoList',
        ),
    ]
